### ISSUE TITLE
Intent of fixing some problem

### ISSUE THREAD

**Issue by szepeviktor** [cipherdevgroup/alpha#10]
Hello!

I'd like to fix some of the problems in your theme.
example output: https://gist.github.com/szepeviktor/ef3c2a259d789b1bcc13c4327ad868e4
using https://packagist.org/packages/szepeviktor/phpstan-wordpress

Are you interested in a PR?

**Comment by robneu** [comment]
Most of these are false positives and any ones that may be actual issues should be dealt with in https://github.com/cipherdevgroup/carelib rather than here.
